# Create a file at .github/workflows/mega-linter.yml in your repository with the following content:


name: MegaLinter

on:
  push:
  pull_request:
    branches: [main]

env:
  APPLY_FIXES: none
  VALIDATE_ALL_CODEBASE: true

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v9
        id: ml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
