# This is a basic workflow to help you get started with Actions

name: Trivy-to run mannually - final demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for vulnerability and Misconfig in IaC
        uses: aquasecurity/trivy-action@98b26b7b56ad844d1316f2693e06f923686cd4e1 #`v0.2.4`
        id: trivy
        continue-on-error: true
        with:
            scan-type: 'config'
            severity: 'HIGH,CRITICAL'
            trivyignores: './.trivyignore'
            exit-code: '1'  # Fail the job if vulnerabilities are found
            output: 'trivy.txt'


      - name: Format Trivy scan result
        run: |
          if [ -s trivy-result.txt ]; then
            echo -e "## 🔍 Trivy Scan Results\n<details><summary>Click to expand</summary>\n\n\`\`\`\n$(cat trivy-result.txt)\n\`\`\`\n</details>" > formatted-trivy-result.md
          else
            echo "## ✅ No vulnerabilities found." > formatted-trivy-result.md
          fi
          
      - name: Comment on PR with Trivy Scan Results
        uses: peter-evans/create-or-update-comment@v5
        with:
            issue-number: ${{ github.event.pull_request.number }}
            body-file: trivy_comment.txt

      - name: Fail if Trivy found high/critical issues
        if: steps.trivy.outcome == 'failure'
        run: |
          echo "❌ Trivy found high or critical issues. Failing the job."
          exit 1
